### PR TITLE
fixed sha1InitState definition

### PR DESCRIPTION
**Pull request by silps**
causes compilation error: variable 'sha1InitState' must be const in order to be put into read-only section by means of '__attribute__((progmem))'

### CODE REVIEW

**Comment by bjpirt** [comment]
Thanks for the pull requests! Just checking, is this to fix the compilation errors in the 1.5.8 beta IDE?

**Comment by silps** [comment]
I got the same error in 1.0.5 and 1.5.7 ^_^

**Comment by bjpirt** [comment]
Weird - it compiles fine for me in 1.0.5, though it does fail in the beta. Which are you using?

**Comment by silps** [comment]
I am using the one that come as a default under Kubuntu 14.04, Arduino Version: 1:1.0.5+dfsg2-2

**Pull request merged**
